const currencyList = [
    { label: 'US Dollar (USD)', value: '$' },
    { label: 'Euro (EUR)', value: '€' },
    { label: 'Indian Rupee (INR)', value: '₹' },
    { label: 'British Pound (GBP)', value: '£' },
    { label: 'Japanese Yen (JPY)', value: '¥' },
    { label: 'Chinese Yuan (CNY)', value: '¥' },
    { label: 'Australian Dollar (AUD)', value: 'A$' },
    { label: 'Canadian Dollar (CAD)', value: 'C$' },
    { label: 'Swiss Franc (CHF)', value: 'CHF' },
    { label: 'Singapore Dollar (SGD)', value: 'S$' },
    { label: 'Hong Kong Dollar (HKD)', value: 'HK$' },
    { label: 'South Korean Won (KRW)', value: '₩' },
    { label: 'New Zealand Dollar (NZD)', value: 'NZ$' },
    { label: 'Swedish Krona (SEK)', value: 'kr' },
    { label: 'Norwegian Krone (NOK)', value: 'kr' },
    { label: 'Danish Krone (DKK)', value: 'kr' },
    { label: 'Mexican Peso (MXN)', value: '$' },
    { label: 'Brazilian Real (BRL)', value: 'R$' },
    { label: 'Russian Ruble (RUB)', value: '₽' },
    { label: 'Turkish Lira (TRY)', value: '₺' },
    { label: 'Thai Baht (THB)', value: '฿' },
    { label: 'UAE Dirham (AED)', value: 'د.إ' },
    { label: 'Israeli Shekel (ILS)', value: '₪' },
    { label: 'Philippine Peso (PHP)', value: '₱' },
    { label: 'South African Rand (ZAR)', value: 'R' },
];

export default currencyList
